### ISSUE TITLE
Installation files server_requirements.txt and requirements.txt are missing from the repository

### ISSUE THREAD

**Issue by P4thF1nd3rz** [vmdiff/vmdiff-prototype#2]
Hello! Thank you very much for contributing this tool to the community.

While following the installation instructions from `README.md`, and looking at `Dockerfile`, it seems the python `requirements.txt` files are missing from the repository (`requirements.txt` for the CLI tools, and `server_requirements.txt` used in `Dockerfile`). 

If this is not intended, would you mind adding these files to the repository please? Many thanks!

**To Reproduce**
Read README.md and follow Installation instructions.

**Expected behavior**
The files are expected to be present in the repository.

**Comment by vmdiff** [comment]
whOOps sorry it's my first day.

They're added now :))
